import it.uniroma2.sel.ebpmn.bpmn.Collaboration;
import it.uniroma2.sel.ebpmn.bpmn.Participant;
import it.uniroma2.sel.ebpmn.bpmn.RemoteNode;
import it.uniroma2.sel.ebpmn.bpmn.events.End;
import it.uniroma2.sel.ebpmn.bpmn.events.IntermediateMessageThrowEvent;
import it.uniroma2.sel.ebpmn.bpmn.events.Start;
import it.uniroma2.sel.ebpmn.bpmn.gateways.ExclusiveConvergingGateway;
import it.uniroma2.sel.ebpmn.bpmn.gateways.ExclusiveDivergingGateway;
import it.uniroma2.sel.ebpmn.bpmn.tasks.Task;
import it.uniroma2.sel.ebpmn.configuration.SimulationConfig;
import it.uniroma2.sel.ebpmn.engine.ExecutionEngine;
import it.uniroma2.sel.ebpmn.generators.ExponentialGenerator;
import it.uniroma2.sel.ebpmn.generators.NormalGenerator;
import it.uniroma2.sel.ebpmn.logger.CSVLogger;
import it.uniroma2.sel.ebpmn.resources.Resource;

import java.io.IOException;


public class Test2_FederateA {

	public static void main(String[] args) {
		
		CSVLogger log = new CSVLogger("src/test/resources/participantA.csv"); //logger
		SimulationConfig config;
		final int MIN=60; //minutes in a second

        try {
			config = SimulationConfig.load("src/test/resources/simulationConfigA.json");
			System.out.println(config.toString());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
		ExecutionEngine engine = ExecutionEngine.initialize(config);

		try {

			/*
			 * Specification of the Collaboration Model
			 *
			 * The interarrival process is assumed to follow an exponential
			 * distribution with lambda = 1/mean value of intearrival time
			 *
			 * The service time of each task is assumed to follow a normal distribution
			 * with parameters μ = mean value and σ = standard deviation
			 *
			 * */

			// ******** Participants *********
			//initiating pool - distributed simulation must use config file to set the participant name
			//while in local simulation any name can be used
			Participant p1 = new Participant(config.getFederateName(), true);

			// ******** Participant 1 *********
			//resources
			Resource r1 = new Resource("Name1", "Office1");
			Resource r2 = new Resource("Name2", "Office2");


			//flow elements
			double rInterarrivalTime = 5*MIN;
			Start s = new Start("Start1", p1,
					new ExponentialGenerator(1/rInterarrivalTime), config.getNumberOfTokens());

			Task task1 = new Task("Task1", p1,
					new NormalGenerator(3.0*MIN, 30));
			task1.addResource(r1);

			ExclusiveDivergingGateway g1d = new ExclusiveDivergingGateway("G1D",p1);

			Task task2 = new Task("Task2", p1,
					new NormalGenerator(5.0*MIN, 20));
			task2.addResource(r2);

			IntermediateMessageThrowEvent imt = new IntermediateMessageThrowEvent("IMT", p1);

			ExclusiveConvergingGateway g1c = new ExclusiveConvergingGateway("G1C",p1);

			End e = new End("End1", p1);

			//flow elements
			s.addOutGoingEdge(task1);
			task1.addOutGoingEdge(g1d);
			g1d.addOutGoingEdge(task2,0.5);
			g1d.addOutGoingEdge(imt,0.5);
			task2.addOutGoingEdge(g1c);
			imt.addOutGoingEdge(g1c);
			g1c.addOutGoingEdge(e);

			//RemoteProxy to Participant B
			RemoteNode imc = new RemoteNode("IMC", new Participant("ParticipantB",false));
			imt.addMessageFlow(imc,"ciao");
			
			//********* BPMN Collaboration model ************ 
			Collaboration model = new Collaboration(config.getFederationName());
			model.addParticipant(p1);
			
						/*
			 * A separated system log is generated by executing the process
			 * specified for each participant of the collaboration model
			 */

			engine.setModel(model);
			engine.setLogger(p1.getName(), log);
			engine.run();


		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
