
import java.io.IOException;
import it.uniroma2.sel.ebpmn.bpmn.*;
import it.uniroma2.sel.ebpmn.bpmn.events.*;
import it.uniroma2.sel.ebpmn.bpmn.gateways.ExclusiveConvergingGateway;
import it.uniroma2.sel.ebpmn.bpmn.gateways.ExclusiveDivergingGateway;
import it.uniroma2.sel.ebpmn.bpmn.tasks.*;
import it.uniroma2.sel.ebpmn.configuration.SimulationConfig;
import it.uniroma2.sel.ebpmn.engine.ExecutionEngine;
import it.uniroma2.sel.ebpmn.logger.CSVLogger;
import it.uniroma2.sel.ebpmn.resources.Performer;
import it.uniroma2.sel.ebpmn.resources.Resource;
import it.uniroma2.sel.ebpmn.generators.ExponentialGenerator;
import it.uniroma2.sel.ebpmn.generators.NormalGenerator;


public class Test1_Local {

	public static void main(String[] args) {

		SimulationConfig config;
		final int MIN=60; //minutes in a second

		try {
			config = SimulationConfig.load("src/test/resources/simulationConfig_Local.json");
			System.out.println(config.toString());
		} catch (IOException e) {
			throw new RuntimeException(e);
		}

		String outputFolder = config.getOutputFolder();
		CSVLogger log = new CSVLogger(outputFolder + "participant_local1.csv"); //logger
		CSVLogger log2 = new CSVLogger(outputFolder + "participant_local2.csv"); //logger

		ExecutionEngine engine = ExecutionEngine.initialize(config);

		try {

			/*
			 * Specification of the Collaboration Model
			 *
			 * The interarrival process is assumed to follow an exponential
			 * distribution with lambda = 1/mean value of intearrival time
			 *
			 * The service time of each task is assumed to follow a normal distribution
			 * with parameters μ = mean value and σ = standard deviation
			 *
			 * */

			// ******** Participants and resources*********
			//initiating pool - distributed simulation must use config file to set the participant name
			//while in local simulation any name can be used
			Participant p1 = new Participant("Participant1", true);
			Participant p2 = new Participant("Participant2",true);
			//resources
			Resource r1 = new Performer("Name1", "role1");
			Resource r2 = new Performer("Name2", "role2");
			Resource r3 = new Performer("Name3", "role2");

			// ******** Participant 1 *********

			//flow elements
			double rInterarrivalTime = 5*MIN;
			Start s = new Start("Start1", p1,
					new ExponentialGenerator(1/rInterarrivalTime), config.getNumberOfTokens());

			Task task1 = new Task("Task1", p1,
					new NormalGenerator(3.0*MIN, 30));
			task1.addResource(r1);

			ExclusiveDivergingGateway g1d = new ExclusiveDivergingGateway("G1D",p1);

			Task task2 = new Task("Task2", p1,
					new NormalGenerator(5.0*MIN, 20));
			task2.addResource(r2);

			IntermediateMessageThrowEvent imt = new IntermediateMessageThrowEvent("IMT", p1);

			ExclusiveConvergingGateway g1c = new ExclusiveConvergingGateway("G1C",p1);
			
			End e = new End("End1", p1);

			//flow elements
			s.addOutGoingEdge(task1);
			task1.addOutGoingEdge(g1d);
			g1d.addOutGoingEdge(task2,0.5);
			g1d.addOutGoingEdge(imt,0.5);
			task2.addOutGoingEdge(g1c);
			imt.addOutGoingEdge(g1c);
			g1c.addOutGoingEdge(e);

			// ******** Participant 2 *********

			//flow elements
			double r2InterarrivalTime = 5.0*MIN;
			Start s2 = new Start("Start2", p2,
					new ExponentialGenerator(1/r2InterarrivalTime), config.getNumberOfTokens());

			IntermediateMessageCatchEvent imc = new IntermediateMessageCatchEvent("IMC",p2);

			Task task3 = new Task("Task3", p2,
					new NormalGenerator(6.0*MIN, 15));
			task3.addResource(r3);

			End e2 = new End("End2", p2);

			//flow elements
			s2.addOutGoingEdge(imc);
			imc.addOutGoingEdge(task3);
			task3.addOutGoingEdge(e2);


			
			//********* BPMN Collaboration model ************ 
			//message flow
			imt.addMessageFlow(imc,"ciao");
			Collaboration model = new Collaboration("Process Model");
			model.addParticipant(p1);
			model.addParticipant(p2);
			
						/*
			 * A separated system log is generated by executing the process
			 * specified for each participant of the collaboration model
			 */
			engine.setModel(model);
			engine.setLogger(p1.getName(), log);
			engine.setLogger(p2.getName(), log2);
			engine.run();


		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
