import it.uniroma2.sel.ebpmn.bpmn.Collaboration;
import it.uniroma2.sel.ebpmn.bpmn.Participant;
import it.uniroma2.sel.ebpmn.bpmn.RemoteNode;
import it.uniroma2.sel.ebpmn.bpmn.events.End;
import it.uniroma2.sel.ebpmn.bpmn.events.IntermediateMessageCatchEvent;
import it.uniroma2.sel.ebpmn.bpmn.events.Start;
import it.uniroma2.sel.ebpmn.bpmn.tasks.ReceiveTask;
import it.uniroma2.sel.ebpmn.bpmn.tasks.SendTask;
import it.uniroma2.sel.ebpmn.bpmn.tasks.Task;
import it.uniroma2.sel.ebpmn.configuration.SimulationConfig;
import it.uniroma2.sel.ebpmn.engine.ExecutionEngine;
import it.uniroma2.sel.ebpmn.generators.ExponentialGenerator;
import it.uniroma2.sel.ebpmn.generators.NormalGenerator;
import it.uniroma2.sel.ebpmn.logger.CSVLogger;
import it.uniroma2.sel.ebpmn.resources.Resource;

import java.io.IOException;


public class Test2_FederateB {

	public static void main(String[] args) {
		
		CSVLogger log = new CSVLogger("src/test/resources/participantB.csv"); //logger
		SimulationConfig config;
		final int MIN=60; //minutes in a second

        try {
			config = SimulationConfig.load("src/test/resources/simulationConfigB.json");
			System.out.println(config.toString());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
		ExecutionEngine engine = ExecutionEngine.initialize(config);

		try {

			/*
			 * Specification of the Collaboration Model
			 *
			 * The interarrival process is assumed to follow an exponential
			 * distribution with lambda = 1/mean value of intearrival time
			 *
			 * The service time of each task is assumed to follow a normal distribution
			 * with parameters μ = mean value and σ = standard deviation
			 *
			 * */

			// ******** Participants *********

			//initiating pool - distributed simulation must use config file to set the participant name
			//while any name can be used in local simulations


			// ******** Participant 2 *********
			//resources
			Resource r3 = new Resource("Name3", "Office3");
			Participant p2 = new Participant(config.getFederateName(),true);


			//flow elements
			double r2InterarrivalTime = 5.0*MIN;
			Start s2 = new Start("Start2", p2,
					new ExponentialGenerator(1/r2InterarrivalTime), config.getNumberOfTokens());

			// imc receives messages from ParticipantA::IMT -
			// remote incoming message links do not need to be included in the model
			// as the hla interaction includes the destination entity
			IntermediateMessageCatchEvent imc = new IntermediateMessageCatchEvent("IMC",p2);

			Task task3 = new Task("Task3", p2,
					new NormalGenerator(6.0*MIN, 15));
			task3.addResource(r3);

			End e2 = new End("End2", p2);

			//flow elements
			s2.addOutGoingEdge(imc);
			imc.addOutGoingEdge(task3);
			task3.addOutGoingEdge(e2);


			//********* BPMN Collaboration model ************ 

			Collaboration model = new Collaboration(config.getFederationName());
			model.addParticipant(p2);

			/*
			 * A separated system log is generated by executing the process
			 * specified for each participant of the collaboration model
			 */
			engine.setModel(model);
			engine.setLogger(p2.getName(), log);
			engine.run();


		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
